# Generated by Django 5.2.7 on 2025-10-23 05:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('ultima_conexion', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('es_creador', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre_usuario'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_membresia', models.CharField(choices=[('BASICA', 'Básica'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], default='BASICA', max_length=10)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membresia', to='app_usuario.usuario')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
